version: '3.8'

services:  
  web:    
    image: httpd:latest    
    container_name: my-apache    
    volumes:      
      - ./html:/usr/local/apache2/htdocs/    
    ports:      
      - "8080:80"